name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  cpp_edlib:
    name: "Check that CPP edlib correctly builds and passes tests."
    strategy:
      matrix:
        arch:
          - x64
          - x86
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set C/CPP compiler to use
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 17
          msbuild-architecture: ${{ matrix.arch }}
      - name: Build
        run: |
          cmake -A ${{ matrix.arch == 'x86' && 'Win32' || matrix.arch }} .
          cmake --build . --config Release
      - name: Test
        run: |
          file bin\Release\runTests.exe
          bin\Release\runTests.exe
