name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  cmake_build:
    name: "CMake build"
    strategy:
      matrix:
        arch:
          - x64
          - x86
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 17
          msbuild-architecture: ${{ matrix.arch }}
      - name: Build
        run: |
          cmake -A ${{ matrix.arch == 'x86' && 'Win32' || matrix.arch }} .
          cmake --build . --config Release
      - name: Test
        run: |
          bin\Release\runTests.exe

  mason_build:
    name: "mason build"
    strategy:
      matrix:
        linking:
          - static
          - shared
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 17
      - name: Build
        run: |
          SPECIFIER=meson-build-${{ matrix.linking }}
          meson setup --backend=ninja -Ddefault_library=${{ matrix.linking }} $SPECIFIER .
          meson compile -v -C $SPECIFIER
      - name: Test
        run: |
          SPECIFIER=meson-build-${{ matrix.linking }}
          meson test -C $SPECIFIER
